# Site settings
title: Acid Rays 
tagline: ""
# baseurl: "/erg-dossier-2022" 
url: http://localhost
baseurl: /

# Use this for production
#sass:
#    style: compressed

exclude: [.scss, README.md, node_modules, gruntfile.js, package.json]

collections:
    projects:
      sort_by: id
      output: true
