# Site settings
title: Acid Rays 
tagline: ""
url: "https://clemtre.github.io" 
# baseurl: "/erg-dossier-2022" 

# Use this for production
#sass:
#    style: compressed

exclude: [.scss, README.md, node_modules, gruntfile.js, package.json]

collections:
    projects:
      sort_by: id
      output: true
